version: 2

jobs:
  build:
    docker: 
      - image: circleci/node:9
    working_directory: ~/repo
    steps: 
      - checkout
      - run: yarn install
      - run: yarn build -pr false
      - run: tar -cf dist.tar dist
      - store_artifacts:
          path: ~/repo/dist.tar
